server:
  port: 8083

spring:

  application:
    name: api-agenda

  datasource:
    url: jdbc:postgresql://postgres:5432/api-agenda-db
    username: api-agenda-user
    password: api-agenda-pass
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

cors:
  allowed:
    origins: http://localhost:4200,http://localhost:3000
